import Head from 'next/head';
import { useAuthState } from 'react-firebase-hooks/auth';
import Sidebar from '../components/Sidebar';
import { auth } from '../firebase';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';

export default function Home() {
  const [user] = useAuthState(auth);
  return (
    <Container>
      <Head>
        <title>whatsapp-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </Container>
  )
}

const Container = styled.div`
`;

